### ISSUE TITLE
Type definition error in ChowErrorMeta

### ISSUE THREAD

**Issue by rozenraymond** [atlassian/oas3-chow-chow#17]
I got an array of object (refer below) for the `rawErrors` property in ChowErrorMeta when validating the request body using the `koa-oas3` middleware.

Received:
```
[ { start: { line: 2, column: 9, offset: 10 },
    end: { line: 2, column: 19, offset: 20 },
    error: '/id: type should be integer',
    path: '/id' } ]
```
However, the type of `rawErrors` property defined in ChowErrorMeta is expecting an array of string instead. 

https://github.com/atlassian/oas3-chow-chow/blob/23ffaee47536b866884f9f53fc89602b1bd397ad/src/error.ts#L3

Is there anyway that this can be fix?

Thanks.

**Comment by supertong** [comment]
Hey @rozenraymond , it should be fixed in this PR.
https://github.com/atlassian/oas3-chow-chow/pull/42
