### ISSUE TITLE
Feature: ability to identify the endpoint by operationId instead of path+method in validateResponse

### ISSUE THREAD

**Issue by naugtur** [atlassian/oas3-chow-chow#18]
When verifying responses path doesn't need to be the basis for validation.
operationId would work better as means to identify which part of the definition to use for verification in tests or anything that runs the validation on responses it got from the server. Path might not be known/available. It might also be harder to obtain in some cases.

Would it be possible to add a validateResponse copy where operationId is used instead of path as the identification?

**Comment by supertong** [comment]
Hey, that makes sense to me because the purpose of the `operationId` is for identifying an operation object.
> Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is RECOMMENDED to follow common programming naming conventions.
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#parameterObject

I am actually thinking where shall we put it in the API. Currently we have
```
interface ResponseMeta {
  method: string;
  status: number;
  header?: any;
  body?: any;
}
validateResponse(path: string, response: ResponseMeta) {
  ...
}
```
what do you think if we make a breaking change to put all things in the `ResponseMeta`?
```
interface ResponseMetaBase {
  method: string;
  status: number;
  header?: any;
  body?: any;
}
interface ResponseMetaWithPath extends ResponseMetaBase {
  path: string;
}

interface ResponseMetaWithOperationId extends ResponseMetaBase {
  operationId: string;
}

type ResponseMeta = ResponseMetaWithPath | ResponseMetaWithOperationId;

validateResponse(path: string, response: ResponseMeta) {
  ...
}
```

Let me know what you think.
Cheers

**Comment by naugtur** [comment]
All my tools I wrote on top of this actually accept operationId and index the API definition to get the fields necessary + some regex magic. That gives me method and a path (sometimes fake) that should match. So this is super useful to me.

Anyway.

It might be too oldschool for this project, but the least breaking way out of this would be to expose a new set of functions. Leave the existing ones and `validate*ByPath` `validate*ByOperationId`.

I've switched to mostly using functions with a single argument that gets destructured inside, so I do like your idea. My first instinct though is to do something like this
```js
validateResponse({ path: string, operationId: string, response: ResponseMeta }) {
  ...
}
```

The interfaces/types of the argument would be defined to require response and one of the other.

The idea with the breaking change has one more advantage though - we could switch `header` to `headers` so I finally stop getting it wrong all the time :D

Let me know which way you'd like to take this and how / if / when I could help. 
Now that Atlassian holds the license I'd probably have to sign something to contribute code.

**Comment by supertong** [comment]
@lukiano @vvvlasov  Do you have any opinion on this? Personally, I prefer `validate*ByPath` and `validate*ByOperationId` as it causes less confusion for the consumer.
Also, do you know if a contributor needs to sign anything in order to contribute?

**Comment by supertong** [comment]
Hey @naugtur , I have included the contributor guide in the readme.

**Comment by naugtur** [comment]
Ok, so I signed it and can help out.
I need some pointers. If you could scaffold it a bit it'd be more likely to look reasonable if I just jumped in ;)

**Comment by naugtur** [comment]
ping

**Comment by supertong** [comment]
Hey @naugtur , hopefully that this can be addressed in #29

**Comment by naugtur** [comment]
Looks good. I should be able to remove all reindexing code from my libs.

I see if I can add some tests to this. I also recall one controversial behavior with default response that I could cover, but that's probably unrelated

**Comment by supertong** [comment]
This has since been implemented.
