### ISSUE TITLE
Response validation should support responses without any content type

### ISSUE THREAD

**Issue by lukiano** [atlassian/oas3-chow-chow#3]
On https://github.com/atlassian/oas3-chow-chow/blob/master/src/compiler/CompiledResponse.ts#L27 
```
    const contentType = CompiledMediaType.extractMediaType(response.header['content-type']);
    if (contentType && this.content[contentType]) {
      return this.content[contentType].validate(response.body);
    } else {
      throw new ChowError('Unsupported Response Media Type', { in: 'response' })
    }
```
if `contentType` is not set, it should just return, instead of throwing an error.

**Comment by supertong** [comment]
Hey @lukiano , just want to clarify the problem a bit.
Do you meant that Content-Type header is not set in the response header or do you meant we don't have a proper Content-Type in the OpenAPI document?

If it's the former, from my opinion, I think it's a good way to tell user that "hey, you don't set your Content-Type" header properly by throwing an error. What do you think?

**Comment by supertong** [comment]
📦 0.8.2
