### ISSUE TITLE
BUG: requestBodyAjvOptions is ignored

### ISSUE THREAD

**Issue by sidtheblue** [atlassian/oas3-chow-chow#35]
The requestBodyAjvOptions are not used when validating requests. They are not passed through to the constructor in CompiledRequestBody.ts, which instead passes an empty object through to the CompiledSchema constructors opts parameter

**Comment by alexkaufman06** [comment]
Looks like crizo23 has a fix for this. Hope this can get merged soon :)

**Comment by supertong** [comment]
Hopefully that this should be resoled with the PR.
