### ISSUE TITLE
Help. Trying to create branch and followup pull request, getting 403

### ISSUE THREAD

**Issue by crizo23** [atlassian/oas3-chow-chow#36]
I signed the CLA. Is there a turnaround time before I'm granted access? Getting: fatal: unable to access 'https://github.com/atlassian/oas3-chow-chow.git/': The requested URL returned error: 403
I tried pushing with SSH, still 403

**Comment by supertong** [comment]
Hey @crizo23 , thanks for contributing. I think you suppose to fork the repo and create the branch in your own repo. And then, you can create the PR from there.

**Comment by crizo23** [comment]
Thanks @supertong !
