### ISSUE TITLE
make use of ajv removeAdditional option

### ISSUE THREAD

**Issue by jardakotesovec** [atlassian/oas3-chow-chow#4]
Hi, thanks for sharing this. We were looking for something that would help us to validate with oas3 and this is very helpful.

It would be very useful for us, if we could also make use of the `removeAdditional` option from ajv. So ajv would filter out inputs/outputs that are not in schema. Is that something you would consider to add to this package? It would probably make sense to have that option separately for headers/cookies/payload/output.

**Comment by supertong** [comment]
Sorry to the late reply, somehow I don't get emails about new issues 🤷‍♂️ 
That looks reasonable to me. I will have a think about how shall I implement this.
Thanks!

**Comment by jardakotesovec** [comment]
@supertong Great. Thanks for feedback, it was actually quick considering that you don't get notified :-). You should be getting emails assuming you watch the repo with that Watch button on top.

**Comment by supertong** [comment]
Hey @jardakotesovec , I have added support to pass down Ajv Options. 🚢 v0.10.0
