### ISSUE TITLE
support for nullable

### ISSUE THREAD

**Issue by jardakotesovec** [atlassian/oas3-chow-chow#5]
Are there plans to support oas3 specifics? Unfortunately they are not following json schema standard so there are some subtle differences. Particularly having issue with [nullable](https://swagger.io/docs/specification/data-models/data-types/):
```
user:
  type: object
  nullable: true
```
It does not get translated to the form ajv (json schema standard) understand.

**Comment by supertong** [comment]
Thanks for pointing that out! This library is specific for OAS3, so yes, I will add changes to support it.

**Comment by supertong** [comment]
Thanks for the info @TageNielsen . We can get this for free after they publish it then.
